package com.sloydev.dependencyinjectionperformance.kodein

import com.sloydev.dependencyinjectionperformance.FibonacciJava
import org.kodein.di.Kodein
import org.kodein.di.erased.bind
import org.kodein.di.erased.instance
import org.kodein.di.erased.provider
import org.kodein.di.erased.singleton

/**
 * Generated with https://gist.github.com/Sloy/12affca1e49ba052053ab4c8bfc5bcb4
 */
val kodeinJavaModule = Kodein.Module(name = "fib") {
    bind<FibonacciJava.Fib1>() with singleton { FibonacciJava.Fib1() }
    bind<FibonacciJava.Fib2>() with singleton { FibonacciJava.Fib2() }
    bind<FibonacciJava.Fib3>() with provider { FibonacciJava.Fib3(instance(), instance()) }
    bind<FibonacciJava.Fib4>() with provider { FibonacciJava.Fib4(instance(), instance()) }
    bind<FibonacciJava.Fib5>() with provider { FibonacciJava.Fib5(instance(), instance()) }
    bind<FibonacciJava.Fib6>() with provider { FibonacciJava.Fib6(instance(), instance()) }
    bind<FibonacciJava.Fib7>() with provider { FibonacciJava.Fib7(instance(), instance()) }
    bind<FibonacciJava.Fib8>() with provider { FibonacciJava.Fib8(instance(), instance()) }
    bind<FibonacciJava.Fib9>() with provider { FibonacciJava.Fib9(instance(), instance()) }
    bind<FibonacciJava.Fib10>() with provider { FibonacciJava.Fib10(instance(), instance()) }
    bind<FibonacciJava.Fib11>() with provider { FibonacciJava.Fib11(instance(), instance()) }
    bind<FibonacciJava.Fib12>() with provider { FibonacciJava.Fib12(instance(), instance()) }
    bind<FibonacciJava.Fib13>() with provider { FibonacciJava.Fib13(instance(), instance()) }
    bind<FibonacciJava.Fib14>() with provider { FibonacciJava.Fib14(instance(), instance()) }
    bind<FibonacciJava.Fib15>() with provider { FibonacciJava.Fib15(instance(), instance()) }
    bind<FibonacciJava.Fib16>() with provider { FibonacciJava.Fib16(instance(), instance()) }
    bind<FibonacciJava.Fib17>() with provider { FibonacciJava.Fib17(instance(), instance()) }
    bind<FibonacciJava.Fib18>() with provider { FibonacciJava.Fib18(instance(), instance()) }
    bind<FibonacciJava.Fib19>() with provider { FibonacciJava.Fib19(instance(), instance()) }
    bind<FibonacciJava.Fib20>() with provider { FibonacciJava.Fib20(instance(), instance()) }
    bind<FibonacciJava.Fib21>() with provider { FibonacciJava.Fib21(instance(), instance()) }
    bind<FibonacciJava.Fib22>() with provider { FibonacciJava.Fib22(instance(), instance()) }
    bind<FibonacciJava.Fib23>() with provider { FibonacciJava.Fib23(instance(), instance()) }
    bind<FibonacciJava.Fib24>() with provider { FibonacciJava.Fib24(instance(), instance()) }
    bind<FibonacciJava.Fib25>() with provider { FibonacciJava.Fib25(instance(), instance()) }
    bind<FibonacciJava.Fib26>() with provider { FibonacciJava.Fib26(instance(), instance()) }
    bind<FibonacciJava.Fib27>() with provider { FibonacciJava.Fib27(instance(), instance()) }
    bind<FibonacciJava.Fib28>() with provider { FibonacciJava.Fib28(instance(), instance()) }
    bind<FibonacciJava.Fib29>() with provider { FibonacciJava.Fib29(instance(), instance()) }
    bind<FibonacciJava.Fib30>() with provider { FibonacciJava.Fib30(instance(), instance()) }
    bind<FibonacciJava.Fib31>() with provider { FibonacciJava.Fib31(instance(), instance()) }
    bind<FibonacciJava.Fib32>() with provider { FibonacciJava.Fib32(instance(), instance()) }
    bind<FibonacciJava.Fib33>() with provider { FibonacciJava.Fib33(instance(), instance()) }
    bind<FibonacciJava.Fib34>() with provider { FibonacciJava.Fib34(instance(), instance()) }
    bind<FibonacciJava.Fib35>() with provider { FibonacciJava.Fib35(instance(), instance()) }
    bind<FibonacciJava.Fib36>() with provider { FibonacciJava.Fib36(instance(), instance()) }
    bind<FibonacciJava.Fib37>() with provider { FibonacciJava.Fib37(instance(), instance()) }
    bind<FibonacciJava.Fib38>() with provider { FibonacciJava.Fib38(instance(), instance()) }
    bind<FibonacciJava.Fib39>() with provider { FibonacciJava.Fib39(instance(), instance()) }
    bind<FibonacciJava.Fib40>() with provider { FibonacciJava.Fib40(instance(), instance()) }
    bind<FibonacciJava.Fib41>() with provider { FibonacciJava.Fib41(instance(), instance()) }
    bind<FibonacciJava.Fib42>() with provider { FibonacciJava.Fib42(instance(), instance()) }
    bind<FibonacciJava.Fib43>() with provider { FibonacciJava.Fib43(instance(), instance()) }
    bind<FibonacciJava.Fib44>() with provider { FibonacciJava.Fib44(instance(), instance()) }
    bind<FibonacciJava.Fib45>() with provider { FibonacciJava.Fib45(instance(), instance()) }
    bind<FibonacciJava.Fib46>() with provider { FibonacciJava.Fib46(instance(), instance()) }
    bind<FibonacciJava.Fib47>() with provider { FibonacciJava.Fib47(instance(), instance()) }
    bind<FibonacciJava.Fib48>() with provider { FibonacciJava.Fib48(instance(), instance()) }
    bind<FibonacciJava.Fib49>() with provider { FibonacciJava.Fib49(instance(), instance()) }
    bind<FibonacciJava.Fib50>() with provider { FibonacciJava.Fib50(instance(), instance()) }
    bind<FibonacciJava.Fib51>() with provider { FibonacciJava.Fib51(instance(), instance()) }
    bind<FibonacciJava.Fib52>() with provider { FibonacciJava.Fib52(instance(), instance()) }
    bind<FibonacciJava.Fib53>() with provider { FibonacciJava.Fib53(instance(), instance()) }
    bind<FibonacciJava.Fib54>() with provider { FibonacciJava.Fib54(instance(), instance()) }
    bind<FibonacciJava.Fib55>() with provider { FibonacciJava.Fib55(instance(), instance()) }
    bind<FibonacciJava.Fib56>() with provider { FibonacciJava.Fib56(instance(), instance()) }
    bind<FibonacciJava.Fib57>() with provider { FibonacciJava.Fib57(instance(), instance()) }
    bind<FibonacciJava.Fib58>() with provider { FibonacciJava.Fib58(instance(), instance()) }
    bind<FibonacciJava.Fib59>() with provider { FibonacciJava.Fib59(instance(), instance()) }
    bind<FibonacciJava.Fib60>() with provider { FibonacciJava.Fib60(instance(), instance()) }
    bind<FibonacciJava.Fib61>() with provider { FibonacciJava.Fib61(instance(), instance()) }
    bind<FibonacciJava.Fib62>() with provider { FibonacciJava.Fib62(instance(), instance()) }
    bind<FibonacciJava.Fib63>() with provider { FibonacciJava.Fib63(instance(), instance()) }
    bind<FibonacciJava.Fib64>() with provider { FibonacciJava.Fib64(instance(), instance()) }
    bind<FibonacciJava.Fib65>() with provider { FibonacciJava.Fib65(instance(), instance()) }
    bind<FibonacciJava.Fib66>() with provider { FibonacciJava.Fib66(instance(), instance()) }
    bind<FibonacciJava.Fib67>() with provider { FibonacciJava.Fib67(instance(), instance()) }
    bind<FibonacciJava.Fib68>() with provider { FibonacciJava.Fib68(instance(), instance()) }
    bind<FibonacciJava.Fib69>() with provider { FibonacciJava.Fib69(instance(), instance()) }
    bind<FibonacciJava.Fib70>() with provider { FibonacciJava.Fib70(instance(), instance()) }
    bind<FibonacciJava.Fib71>() with provider { FibonacciJava.Fib71(instance(), instance()) }
    bind<FibonacciJava.Fib72>() with provider { FibonacciJava.Fib72(instance(), instance()) }
    bind<FibonacciJava.Fib73>() with provider { FibonacciJava.Fib73(instance(), instance()) }
    bind<FibonacciJava.Fib74>() with provider { FibonacciJava.Fib74(instance(), instance()) }
    bind<FibonacciJava.Fib75>() with provider { FibonacciJava.Fib75(instance(), instance()) }
    bind<FibonacciJava.Fib76>() with provider { FibonacciJava.Fib76(instance(), instance()) }
    bind<FibonacciJava.Fib77>() with provider { FibonacciJava.Fib77(instance(), instance()) }
    bind<FibonacciJava.Fib78>() with provider { FibonacciJava.Fib78(instance(), instance()) }
    bind<FibonacciJava.Fib79>() with provider { FibonacciJava.Fib79(instance(), instance()) }
    bind<FibonacciJava.Fib80>() with provider { FibonacciJava.Fib80(instance(), instance()) }
    bind<FibonacciJava.Fib81>() with provider { FibonacciJava.Fib81(instance(), instance()) }
    bind<FibonacciJava.Fib82>() with provider { FibonacciJava.Fib82(instance(), instance()) }
    bind<FibonacciJava.Fib83>() with provider { FibonacciJava.Fib83(instance(), instance()) }
    bind<FibonacciJava.Fib84>() with provider { FibonacciJava.Fib84(instance(), instance()) }
    bind<FibonacciJava.Fib85>() with provider { FibonacciJava.Fib85(instance(), instance()) }
    bind<FibonacciJava.Fib86>() with provider { FibonacciJava.Fib86(instance(), instance()) }
    bind<FibonacciJava.Fib87>() with provider { FibonacciJava.Fib87(instance(), instance()) }
    bind<FibonacciJava.Fib88>() with provider { FibonacciJava.Fib88(instance(), instance()) }
    bind<FibonacciJava.Fib89>() with provider { FibonacciJava.Fib89(instance(), instance()) }
    bind<FibonacciJava.Fib90>() with provider { FibonacciJava.Fib90(instance(), instance()) }
    bind<FibonacciJava.Fib91>() with provider { FibonacciJava.Fib91(instance(), instance()) }
    bind<FibonacciJava.Fib92>() with provider { FibonacciJava.Fib92(instance(), instance()) }
    bind<FibonacciJava.Fib93>() with provider { FibonacciJava.Fib93(instance(), instance()) }
    bind<FibonacciJava.Fib94>() with provider { FibonacciJava.Fib94(instance(), instance()) }
    bind<FibonacciJava.Fib95>() with provider { FibonacciJava.Fib95(instance(), instance()) }
    bind<FibonacciJava.Fib96>() with provider { FibonacciJava.Fib96(instance(), instance()) }
    bind<FibonacciJava.Fib97>() with provider { FibonacciJava.Fib97(instance(), instance()) }
    bind<FibonacciJava.Fib98>() with provider { FibonacciJava.Fib98(instance(), instance()) }
    bind<FibonacciJava.Fib99>() with provider { FibonacciJava.Fib99(instance(), instance()) }
    bind<FibonacciJava.Fib100>() with provider { FibonacciJava.Fib100(instance(), instance()) }
    bind<FibonacciJava.Fib101>() with provider { FibonacciJava.Fib101(instance(), instance()) }
    bind<FibonacciJava.Fib102>() with provider { FibonacciJava.Fib102(instance(), instance()) }
    bind<FibonacciJava.Fib103>() with provider { FibonacciJava.Fib103(instance(), instance()) }
    bind<FibonacciJava.Fib104>() with provider { FibonacciJava.Fib104(instance(), instance()) }
    bind<FibonacciJava.Fib105>() with provider { FibonacciJava.Fib105(instance(), instance()) }
    bind<FibonacciJava.Fib106>() with provider { FibonacciJava.Fib106(instance(), instance()) }
    bind<FibonacciJava.Fib107>() with provider { FibonacciJava.Fib107(instance(), instance()) }
    bind<FibonacciJava.Fib108>() with provider { FibonacciJava.Fib108(instance(), instance()) }
    bind<FibonacciJava.Fib109>() with provider { FibonacciJava.Fib109(instance(), instance()) }
    bind<FibonacciJava.Fib110>() with provider { FibonacciJava.Fib110(instance(), instance()) }
    bind<FibonacciJava.Fib111>() with provider { FibonacciJava.Fib111(instance(), instance()) }
    bind<FibonacciJava.Fib112>() with provider { FibonacciJava.Fib112(instance(), instance()) }
    bind<FibonacciJava.Fib113>() with provider { FibonacciJava.Fib113(instance(), instance()) }
    bind<FibonacciJava.Fib114>() with provider { FibonacciJava.Fib114(instance(), instance()) }
    bind<FibonacciJava.Fib115>() with provider { FibonacciJava.Fib115(instance(), instance()) }
    bind<FibonacciJava.Fib116>() with provider { FibonacciJava.Fib116(instance(), instance()) }
    bind<FibonacciJava.Fib117>() with provider { FibonacciJava.Fib117(instance(), instance()) }
    bind<FibonacciJava.Fib118>() with provider { FibonacciJava.Fib118(instance(), instance()) }
    bind<FibonacciJava.Fib119>() with provider { FibonacciJava.Fib119(instance(), instance()) }
    bind<FibonacciJava.Fib120>() with provider { FibonacciJava.Fib120(instance(), instance()) }
    bind<FibonacciJava.Fib121>() with provider { FibonacciJava.Fib121(instance(), instance()) }
    bind<FibonacciJava.Fib122>() with provider { FibonacciJava.Fib122(instance(), instance()) }
    bind<FibonacciJava.Fib123>() with provider { FibonacciJava.Fib123(instance(), instance()) }
    bind<FibonacciJava.Fib124>() with provider { FibonacciJava.Fib124(instance(), instance()) }
    bind<FibonacciJava.Fib125>() with provider { FibonacciJava.Fib125(instance(), instance()) }
    bind<FibonacciJava.Fib126>() with provider { FibonacciJava.Fib126(instance(), instance()) }
    bind<FibonacciJava.Fib127>() with provider { FibonacciJava.Fib127(instance(), instance()) }
    bind<FibonacciJava.Fib128>() with provider { FibonacciJava.Fib128(instance(), instance()) }
    bind<FibonacciJava.Fib129>() with provider { FibonacciJava.Fib129(instance(), instance()) }
    bind<FibonacciJava.Fib130>() with provider { FibonacciJava.Fib130(instance(), instance()) }
    bind<FibonacciJava.Fib131>() with provider { FibonacciJava.Fib131(instance(), instance()) }
    bind<FibonacciJava.Fib132>() with provider { FibonacciJava.Fib132(instance(), instance()) }
    bind<FibonacciJava.Fib133>() with provider { FibonacciJava.Fib133(instance(), instance()) }
    bind<FibonacciJava.Fib134>() with provider { FibonacciJava.Fib134(instance(), instance()) }
    bind<FibonacciJava.Fib135>() with provider { FibonacciJava.Fib135(instance(), instance()) }
    bind<FibonacciJava.Fib136>() with provider { FibonacciJava.Fib136(instance(), instance()) }
    bind<FibonacciJava.Fib137>() with provider { FibonacciJava.Fib137(instance(), instance()) }
    bind<FibonacciJava.Fib138>() with provider { FibonacciJava.Fib138(instance(), instance()) }
    bind<FibonacciJava.Fib139>() with provider { FibonacciJava.Fib139(instance(), instance()) }
    bind<FibonacciJava.Fib140>() with provider { FibonacciJava.Fib140(instance(), instance()) }
    bind<FibonacciJava.Fib141>() with provider { FibonacciJava.Fib141(instance(), instance()) }
    bind<FibonacciJava.Fib142>() with provider { FibonacciJava.Fib142(instance(), instance()) }
    bind<FibonacciJava.Fib143>() with provider { FibonacciJava.Fib143(instance(), instance()) }
    bind<FibonacciJava.Fib144>() with provider { FibonacciJava.Fib144(instance(), instance()) }
    bind<FibonacciJava.Fib145>() with provider { FibonacciJava.Fib145(instance(), instance()) }
    bind<FibonacciJava.Fib146>() with provider { FibonacciJava.Fib146(instance(), instance()) }
    bind<FibonacciJava.Fib147>() with provider { FibonacciJava.Fib147(instance(), instance()) }
    bind<FibonacciJava.Fib148>() with provider { FibonacciJava.Fib148(instance(), instance()) }
    bind<FibonacciJava.Fib149>() with provider { FibonacciJava.Fib149(instance(), instance()) }
    bind<FibonacciJava.Fib150>() with provider { FibonacciJava.Fib150(instance(), instance()) }
    bind<FibonacciJava.Fib151>() with provider { FibonacciJava.Fib151(instance(), instance()) }
    bind<FibonacciJava.Fib152>() with provider { FibonacciJava.Fib152(instance(), instance()) }
    bind<FibonacciJava.Fib153>() with provider { FibonacciJava.Fib153(instance(), instance()) }
    bind<FibonacciJava.Fib154>() with provider { FibonacciJava.Fib154(instance(), instance()) }
    bind<FibonacciJava.Fib155>() with provider { FibonacciJava.Fib155(instance(), instance()) }
    bind<FibonacciJava.Fib156>() with provider { FibonacciJava.Fib156(instance(), instance()) }
    bind<FibonacciJava.Fib157>() with provider { FibonacciJava.Fib157(instance(), instance()) }
    bind<FibonacciJava.Fib158>() with provider { FibonacciJava.Fib158(instance(), instance()) }
    bind<FibonacciJava.Fib159>() with provider { FibonacciJava.Fib159(instance(), instance()) }
    bind<FibonacciJava.Fib160>() with provider { FibonacciJava.Fib160(instance(), instance()) }
    bind<FibonacciJava.Fib161>() with provider { FibonacciJava.Fib161(instance(), instance()) }
    bind<FibonacciJava.Fib162>() with provider { FibonacciJava.Fib162(instance(), instance()) }
    bind<FibonacciJava.Fib163>() with provider { FibonacciJava.Fib163(instance(), instance()) }
    bind<FibonacciJava.Fib164>() with provider { FibonacciJava.Fib164(instance(), instance()) }
    bind<FibonacciJava.Fib165>() with provider { FibonacciJava.Fib165(instance(), instance()) }
    bind<FibonacciJava.Fib166>() with provider { FibonacciJava.Fib166(instance(), instance()) }
    bind<FibonacciJava.Fib167>() with provider { FibonacciJava.Fib167(instance(), instance()) }
    bind<FibonacciJava.Fib168>() with provider { FibonacciJava.Fib168(instance(), instance()) }
    bind<FibonacciJava.Fib169>() with provider { FibonacciJava.Fib169(instance(), instance()) }
    bind<FibonacciJava.Fib170>() with provider { FibonacciJava.Fib170(instance(), instance()) }
    bind<FibonacciJava.Fib171>() with provider { FibonacciJava.Fib171(instance(), instance()) }
    bind<FibonacciJava.Fib172>() with provider { FibonacciJava.Fib172(instance(), instance()) }
    bind<FibonacciJava.Fib173>() with provider { FibonacciJava.Fib173(instance(), instance()) }
    bind<FibonacciJava.Fib174>() with provider { FibonacciJava.Fib174(instance(), instance()) }
    bind<FibonacciJava.Fib175>() with provider { FibonacciJava.Fib175(instance(), instance()) }
    bind<FibonacciJava.Fib176>() with provider { FibonacciJava.Fib176(instance(), instance()) }
    bind<FibonacciJava.Fib177>() with provider { FibonacciJava.Fib177(instance(), instance()) }
    bind<FibonacciJava.Fib178>() with provider { FibonacciJava.Fib178(instance(), instance()) }
    bind<FibonacciJava.Fib179>() with provider { FibonacciJava.Fib179(instance(), instance()) }
    bind<FibonacciJava.Fib180>() with provider { FibonacciJava.Fib180(instance(), instance()) }
    bind<FibonacciJava.Fib181>() with provider { FibonacciJava.Fib181(instance(), instance()) }
    bind<FibonacciJava.Fib182>() with provider { FibonacciJava.Fib182(instance(), instance()) }
    bind<FibonacciJava.Fib183>() with provider { FibonacciJava.Fib183(instance(), instance()) }
    bind<FibonacciJava.Fib184>() with provider { FibonacciJava.Fib184(instance(), instance()) }
    bind<FibonacciJava.Fib185>() with provider { FibonacciJava.Fib185(instance(), instance()) }
    bind<FibonacciJava.Fib186>() with provider { FibonacciJava.Fib186(instance(), instance()) }
    bind<FibonacciJava.Fib187>() with provider { FibonacciJava.Fib187(instance(), instance()) }
    bind<FibonacciJava.Fib188>() with provider { FibonacciJava.Fib188(instance(), instance()) }
    bind<FibonacciJava.Fib189>() with provider { FibonacciJava.Fib189(instance(), instance()) }
    bind<FibonacciJava.Fib190>() with provider { FibonacciJava.Fib190(instance(), instance()) }
    bind<FibonacciJava.Fib191>() with provider { FibonacciJava.Fib191(instance(), instance()) }
    bind<FibonacciJava.Fib192>() with provider { FibonacciJava.Fib192(instance(), instance()) }
    bind<FibonacciJava.Fib193>() with provider { FibonacciJava.Fib193(instance(), instance()) }
    bind<FibonacciJava.Fib194>() with provider { FibonacciJava.Fib194(instance(), instance()) }
    bind<FibonacciJava.Fib195>() with provider { FibonacciJava.Fib195(instance(), instance()) }
    bind<FibonacciJava.Fib196>() with provider { FibonacciJava.Fib196(instance(), instance()) }
    bind<FibonacciJava.Fib197>() with provider { FibonacciJava.Fib197(instance(), instance()) }
    bind<FibonacciJava.Fib198>() with provider { FibonacciJava.Fib198(instance(), instance()) }
    bind<FibonacciJava.Fib199>() with provider { FibonacciJava.Fib199(instance(), instance()) }
    bind<FibonacciJava.Fib200>() with provider { FibonacciJava.Fib200(instance(), instance()) }
    bind<FibonacciJava.Fib201>() with provider { FibonacciJava.Fib201(instance(), instance()) }
    bind<FibonacciJava.Fib202>() with provider { FibonacciJava.Fib202(instance(), instance()) }
    bind<FibonacciJava.Fib203>() with provider { FibonacciJava.Fib203(instance(), instance()) }
    bind<FibonacciJava.Fib204>() with provider { FibonacciJava.Fib204(instance(), instance()) }
    bind<FibonacciJava.Fib205>() with provider { FibonacciJava.Fib205(instance(), instance()) }
    bind<FibonacciJava.Fib206>() with provider { FibonacciJava.Fib206(instance(), instance()) }
    bind<FibonacciJava.Fib207>() with provider { FibonacciJava.Fib207(instance(), instance()) }
    bind<FibonacciJava.Fib208>() with provider { FibonacciJava.Fib208(instance(), instance()) }
    bind<FibonacciJava.Fib209>() with provider { FibonacciJava.Fib209(instance(), instance()) }
    bind<FibonacciJava.Fib210>() with provider { FibonacciJava.Fib210(instance(), instance()) }
    bind<FibonacciJava.Fib211>() with provider { FibonacciJava.Fib211(instance(), instance()) }
    bind<FibonacciJava.Fib212>() with provider { FibonacciJava.Fib212(instance(), instance()) }
    bind<FibonacciJava.Fib213>() with provider { FibonacciJava.Fib213(instance(), instance()) }
    bind<FibonacciJava.Fib214>() with provider { FibonacciJava.Fib214(instance(), instance()) }
    bind<FibonacciJava.Fib215>() with provider { FibonacciJava.Fib215(instance(), instance()) }
    bind<FibonacciJava.Fib216>() with provider { FibonacciJava.Fib216(instance(), instance()) }
    bind<FibonacciJava.Fib217>() with provider { FibonacciJava.Fib217(instance(), instance()) }
    bind<FibonacciJava.Fib218>() with provider { FibonacciJava.Fib218(instance(), instance()) }
    bind<FibonacciJava.Fib219>() with provider { FibonacciJava.Fib219(instance(), instance()) }
    bind<FibonacciJava.Fib220>() with provider { FibonacciJava.Fib220(instance(), instance()) }
    bind<FibonacciJava.Fib221>() with provider { FibonacciJava.Fib221(instance(), instance()) }
    bind<FibonacciJava.Fib222>() with provider { FibonacciJava.Fib222(instance(), instance()) }
    bind<FibonacciJava.Fib223>() with provider { FibonacciJava.Fib223(instance(), instance()) }
    bind<FibonacciJava.Fib224>() with provider { FibonacciJava.Fib224(instance(), instance()) }
    bind<FibonacciJava.Fib225>() with provider { FibonacciJava.Fib225(instance(), instance()) }
    bind<FibonacciJava.Fib226>() with provider { FibonacciJava.Fib226(instance(), instance()) }
    bind<FibonacciJava.Fib227>() with provider { FibonacciJava.Fib227(instance(), instance()) }
    bind<FibonacciJava.Fib228>() with provider { FibonacciJava.Fib228(instance(), instance()) }
    bind<FibonacciJava.Fib229>() with provider { FibonacciJava.Fib229(instance(), instance()) }
    bind<FibonacciJava.Fib230>() with provider { FibonacciJava.Fib230(instance(), instance()) }
    bind<FibonacciJava.Fib231>() with provider { FibonacciJava.Fib231(instance(), instance()) }
    bind<FibonacciJava.Fib232>() with provider { FibonacciJava.Fib232(instance(), instance()) }
    bind<FibonacciJava.Fib233>() with provider { FibonacciJava.Fib233(instance(), instance()) }
    bind<FibonacciJava.Fib234>() with provider { FibonacciJava.Fib234(instance(), instance()) }
    bind<FibonacciJava.Fib235>() with provider { FibonacciJava.Fib235(instance(), instance()) }
    bind<FibonacciJava.Fib236>() with provider { FibonacciJava.Fib236(instance(), instance()) }
    bind<FibonacciJava.Fib237>() with provider { FibonacciJava.Fib237(instance(), instance()) }
    bind<FibonacciJava.Fib238>() with provider { FibonacciJava.Fib238(instance(), instance()) }
    bind<FibonacciJava.Fib239>() with provider { FibonacciJava.Fib239(instance(), instance()) }
    bind<FibonacciJava.Fib240>() with provider { FibonacciJava.Fib240(instance(), instance()) }
    bind<FibonacciJava.Fib241>() with provider { FibonacciJava.Fib241(instance(), instance()) }
    bind<FibonacciJava.Fib242>() with provider { FibonacciJava.Fib242(instance(), instance()) }
    bind<FibonacciJava.Fib243>() with provider { FibonacciJava.Fib243(instance(), instance()) }
    bind<FibonacciJava.Fib244>() with provider { FibonacciJava.Fib244(instance(), instance()) }
    bind<FibonacciJava.Fib245>() with provider { FibonacciJava.Fib245(instance(), instance()) }
    bind<FibonacciJava.Fib246>() with provider { FibonacciJava.Fib246(instance(), instance()) }
    bind<FibonacciJava.Fib247>() with provider { FibonacciJava.Fib247(instance(), instance()) }
    bind<FibonacciJava.Fib248>() with provider { FibonacciJava.Fib248(instance(), instance()) }
    bind<FibonacciJava.Fib249>() with provider { FibonacciJava.Fib249(instance(), instance()) }
    bind<FibonacciJava.Fib250>() with provider { FibonacciJava.Fib250(instance(), instance()) }
    bind<FibonacciJava.Fib251>() with provider { FibonacciJava.Fib251(instance(), instance()) }
    bind<FibonacciJava.Fib252>() with provider { FibonacciJava.Fib252(instance(), instance()) }
    bind<FibonacciJava.Fib253>() with provider { FibonacciJava.Fib253(instance(), instance()) }
    bind<FibonacciJava.Fib254>() with provider { FibonacciJava.Fib254(instance(), instance()) }
    bind<FibonacciJava.Fib255>() with provider { FibonacciJava.Fib255(instance(), instance()) }
    bind<FibonacciJava.Fib256>() with provider { FibonacciJava.Fib256(instance(), instance()) }
    bind<FibonacciJava.Fib257>() with provider { FibonacciJava.Fib257(instance(), instance()) }
    bind<FibonacciJava.Fib258>() with provider { FibonacciJava.Fib258(instance(), instance()) }
    bind<FibonacciJava.Fib259>() with provider { FibonacciJava.Fib259(instance(), instance()) }
    bind<FibonacciJava.Fib260>() with provider { FibonacciJava.Fib260(instance(), instance()) }
    bind<FibonacciJava.Fib261>() with provider { FibonacciJava.Fib261(instance(), instance()) }
    bind<FibonacciJava.Fib262>() with provider { FibonacciJava.Fib262(instance(), instance()) }
    bind<FibonacciJava.Fib263>() with provider { FibonacciJava.Fib263(instance(), instance()) }
    bind<FibonacciJava.Fib264>() with provider { FibonacciJava.Fib264(instance(), instance()) }
    bind<FibonacciJava.Fib265>() with provider { FibonacciJava.Fib265(instance(), instance()) }
    bind<FibonacciJava.Fib266>() with provider { FibonacciJava.Fib266(instance(), instance()) }
    bind<FibonacciJava.Fib267>() with provider { FibonacciJava.Fib267(instance(), instance()) }
    bind<FibonacciJava.Fib268>() with provider { FibonacciJava.Fib268(instance(), instance()) }
    bind<FibonacciJava.Fib269>() with provider { FibonacciJava.Fib269(instance(), instance()) }
    bind<FibonacciJava.Fib270>() with provider { FibonacciJava.Fib270(instance(), instance()) }
    bind<FibonacciJava.Fib271>() with provider { FibonacciJava.Fib271(instance(), instance()) }
    bind<FibonacciJava.Fib272>() with provider { FibonacciJava.Fib272(instance(), instance()) }
    bind<FibonacciJava.Fib273>() with provider { FibonacciJava.Fib273(instance(), instance()) }
    bind<FibonacciJava.Fib274>() with provider { FibonacciJava.Fib274(instance(), instance()) }
    bind<FibonacciJava.Fib275>() with provider { FibonacciJava.Fib275(instance(), instance()) }
    bind<FibonacciJava.Fib276>() with provider { FibonacciJava.Fib276(instance(), instance()) }
    bind<FibonacciJava.Fib277>() with provider { FibonacciJava.Fib277(instance(), instance()) }
    bind<FibonacciJava.Fib278>() with provider { FibonacciJava.Fib278(instance(), instance()) }
    bind<FibonacciJava.Fib279>() with provider { FibonacciJava.Fib279(instance(), instance()) }
    bind<FibonacciJava.Fib280>() with provider { FibonacciJava.Fib280(instance(), instance()) }
    bind<FibonacciJava.Fib281>() with provider { FibonacciJava.Fib281(instance(), instance()) }
    bind<FibonacciJava.Fib282>() with provider { FibonacciJava.Fib282(instance(), instance()) }
    bind<FibonacciJava.Fib283>() with provider { FibonacciJava.Fib283(instance(), instance()) }
    bind<FibonacciJava.Fib284>() with provider { FibonacciJava.Fib284(instance(), instance()) }
    bind<FibonacciJava.Fib285>() with provider { FibonacciJava.Fib285(instance(), instance()) }
    bind<FibonacciJava.Fib286>() with provider { FibonacciJava.Fib286(instance(), instance()) }
    bind<FibonacciJava.Fib287>() with provider { FibonacciJava.Fib287(instance(), instance()) }
    bind<FibonacciJava.Fib288>() with provider { FibonacciJava.Fib288(instance(), instance()) }
    bind<FibonacciJava.Fib289>() with provider { FibonacciJava.Fib289(instance(), instance()) }
    bind<FibonacciJava.Fib290>() with provider { FibonacciJava.Fib290(instance(), instance()) }
    bind<FibonacciJava.Fib291>() with provider { FibonacciJava.Fib291(instance(), instance()) }
    bind<FibonacciJava.Fib292>() with provider { FibonacciJava.Fib292(instance(), instance()) }
    bind<FibonacciJava.Fib293>() with provider { FibonacciJava.Fib293(instance(), instance()) }
    bind<FibonacciJava.Fib294>() with provider { FibonacciJava.Fib294(instance(), instance()) }
    bind<FibonacciJava.Fib295>() with provider { FibonacciJava.Fib295(instance(), instance()) }
    bind<FibonacciJava.Fib296>() with provider { FibonacciJava.Fib296(instance(), instance()) }
    bind<FibonacciJava.Fib297>() with provider { FibonacciJava.Fib297(instance(), instance()) }
    bind<FibonacciJava.Fib298>() with provider { FibonacciJava.Fib298(instance(), instance()) }
    bind<FibonacciJava.Fib299>() with provider { FibonacciJava.Fib299(instance(), instance()) }
    bind<FibonacciJava.Fib300>() with provider { FibonacciJava.Fib300(instance(), instance()) }
    bind<FibonacciJava.Fib301>() with provider { FibonacciJava.Fib301(instance(), instance()) }
    bind<FibonacciJava.Fib302>() with provider { FibonacciJava.Fib302(instance(), instance()) }
    bind<FibonacciJava.Fib303>() with provider { FibonacciJava.Fib303(instance(), instance()) }
    bind<FibonacciJava.Fib304>() with provider { FibonacciJava.Fib304(instance(), instance()) }
    bind<FibonacciJava.Fib305>() with provider { FibonacciJava.Fib305(instance(), instance()) }
    bind<FibonacciJava.Fib306>() with provider { FibonacciJava.Fib306(instance(), instance()) }
    bind<FibonacciJava.Fib307>() with provider { FibonacciJava.Fib307(instance(), instance()) }
    bind<FibonacciJava.Fib308>() with provider { FibonacciJava.Fib308(instance(), instance()) }
    bind<FibonacciJava.Fib309>() with provider { FibonacciJava.Fib309(instance(), instance()) }
    bind<FibonacciJava.Fib310>() with provider { FibonacciJava.Fib310(instance(), instance()) }
    bind<FibonacciJava.Fib311>() with provider { FibonacciJava.Fib311(instance(), instance()) }
    bind<FibonacciJava.Fib312>() with provider { FibonacciJava.Fib312(instance(), instance()) }
    bind<FibonacciJava.Fib313>() with provider { FibonacciJava.Fib313(instance(), instance()) }
    bind<FibonacciJava.Fib314>() with provider { FibonacciJava.Fib314(instance(), instance()) }
    bind<FibonacciJava.Fib315>() with provider { FibonacciJava.Fib315(instance(), instance()) }
    bind<FibonacciJava.Fib316>() with provider { FibonacciJava.Fib316(instance(), instance()) }
    bind<FibonacciJava.Fib317>() with provider { FibonacciJava.Fib317(instance(), instance()) }
    bind<FibonacciJava.Fib318>() with provider { FibonacciJava.Fib318(instance(), instance()) }
    bind<FibonacciJava.Fib319>() with provider { FibonacciJava.Fib319(instance(), instance()) }
    bind<FibonacciJava.Fib320>() with provider { FibonacciJava.Fib320(instance(), instance()) }
    bind<FibonacciJava.Fib321>() with provider { FibonacciJava.Fib321(instance(), instance()) }
    bind<FibonacciJava.Fib322>() with provider { FibonacciJava.Fib322(instance(), instance()) }
    bind<FibonacciJava.Fib323>() with provider { FibonacciJava.Fib323(instance(), instance()) }
    bind<FibonacciJava.Fib324>() with provider { FibonacciJava.Fib324(instance(), instance()) }
    bind<FibonacciJava.Fib325>() with provider { FibonacciJava.Fib325(instance(), instance()) }
    bind<FibonacciJava.Fib326>() with provider { FibonacciJava.Fib326(instance(), instance()) }
    bind<FibonacciJava.Fib327>() with provider { FibonacciJava.Fib327(instance(), instance()) }
    bind<FibonacciJava.Fib328>() with provider { FibonacciJava.Fib328(instance(), instance()) }
    bind<FibonacciJava.Fib329>() with provider { FibonacciJava.Fib329(instance(), instance()) }
    bind<FibonacciJava.Fib330>() with provider { FibonacciJava.Fib330(instance(), instance()) }
    bind<FibonacciJava.Fib331>() with provider { FibonacciJava.Fib331(instance(), instance()) }
    bind<FibonacciJava.Fib332>() with provider { FibonacciJava.Fib332(instance(), instance()) }
    bind<FibonacciJava.Fib333>() with provider { FibonacciJava.Fib333(instance(), instance()) }
    bind<FibonacciJava.Fib334>() with provider { FibonacciJava.Fib334(instance(), instance()) }
    bind<FibonacciJava.Fib335>() with provider { FibonacciJava.Fib335(instance(), instance()) }
    bind<FibonacciJava.Fib336>() with provider { FibonacciJava.Fib336(instance(), instance()) }
    bind<FibonacciJava.Fib337>() with provider { FibonacciJava.Fib337(instance(), instance()) }
    bind<FibonacciJava.Fib338>() with provider { FibonacciJava.Fib338(instance(), instance()) }
    bind<FibonacciJava.Fib339>() with provider { FibonacciJava.Fib339(instance(), instance()) }
    bind<FibonacciJava.Fib340>() with provider { FibonacciJava.Fib340(instance(), instance()) }
    bind<FibonacciJava.Fib341>() with provider { FibonacciJava.Fib341(instance(), instance()) }
    bind<FibonacciJava.Fib342>() with provider { FibonacciJava.Fib342(instance(), instance()) }
    bind<FibonacciJava.Fib343>() with provider { FibonacciJava.Fib343(instance(), instance()) }
    bind<FibonacciJava.Fib344>() with provider { FibonacciJava.Fib344(instance(), instance()) }
    bind<FibonacciJava.Fib345>() with provider { FibonacciJava.Fib345(instance(), instance()) }
    bind<FibonacciJava.Fib346>() with provider { FibonacciJava.Fib346(instance(), instance()) }
    bind<FibonacciJava.Fib347>() with provider { FibonacciJava.Fib347(instance(), instance()) }
    bind<FibonacciJava.Fib348>() with provider { FibonacciJava.Fib348(instance(), instance()) }
    bind<FibonacciJava.Fib349>() with provider { FibonacciJava.Fib349(instance(), instance()) }
    bind<FibonacciJava.Fib350>() with provider { FibonacciJava.Fib350(instance(), instance()) }
    bind<FibonacciJava.Fib351>() with provider { FibonacciJava.Fib351(instance(), instance()) }
    bind<FibonacciJava.Fib352>() with provider { FibonacciJava.Fib352(instance(), instance()) }
    bind<FibonacciJava.Fib353>() with provider { FibonacciJava.Fib353(instance(), instance()) }
    bind<FibonacciJava.Fib354>() with provider { FibonacciJava.Fib354(instance(), instance()) }
    bind<FibonacciJava.Fib355>() with provider { FibonacciJava.Fib355(instance(), instance()) }
    bind<FibonacciJava.Fib356>() with provider { FibonacciJava.Fib356(instance(), instance()) }
    bind<FibonacciJava.Fib357>() with provider { FibonacciJava.Fib357(instance(), instance()) }
    bind<FibonacciJava.Fib358>() with provider { FibonacciJava.Fib358(instance(), instance()) }
    bind<FibonacciJava.Fib359>() with provider { FibonacciJava.Fib359(instance(), instance()) }
    bind<FibonacciJava.Fib360>() with provider { FibonacciJava.Fib360(instance(), instance()) }
    bind<FibonacciJava.Fib361>() with provider { FibonacciJava.Fib361(instance(), instance()) }
    bind<FibonacciJava.Fib362>() with provider { FibonacciJava.Fib362(instance(), instance()) }
    bind<FibonacciJava.Fib363>() with provider { FibonacciJava.Fib363(instance(), instance()) }
    bind<FibonacciJava.Fib364>() with provider { FibonacciJava.Fib364(instance(), instance()) }
    bind<FibonacciJava.Fib365>() with provider { FibonacciJava.Fib365(instance(), instance()) }
    bind<FibonacciJava.Fib366>() with provider { FibonacciJava.Fib366(instance(), instance()) }
    bind<FibonacciJava.Fib367>() with provider { FibonacciJava.Fib367(instance(), instance()) }
    bind<FibonacciJava.Fib368>() with provider { FibonacciJava.Fib368(instance(), instance()) }
    bind<FibonacciJava.Fib369>() with provider { FibonacciJava.Fib369(instance(), instance()) }
    bind<FibonacciJava.Fib370>() with provider { FibonacciJava.Fib370(instance(), instance()) }
    bind<FibonacciJava.Fib371>() with provider { FibonacciJava.Fib371(instance(), instance()) }
    bind<FibonacciJava.Fib372>() with provider { FibonacciJava.Fib372(instance(), instance()) }
    bind<FibonacciJava.Fib373>() with provider { FibonacciJava.Fib373(instance(), instance()) }
    bind<FibonacciJava.Fib374>() with provider { FibonacciJava.Fib374(instance(), instance()) }
    bind<FibonacciJava.Fib375>() with provider { FibonacciJava.Fib375(instance(), instance()) }
    bind<FibonacciJava.Fib376>() with provider { FibonacciJava.Fib376(instance(), instance()) }
    bind<FibonacciJava.Fib377>() with provider { FibonacciJava.Fib377(instance(), instance()) }
    bind<FibonacciJava.Fib378>() with provider { FibonacciJava.Fib378(instance(), instance()) }
    bind<FibonacciJava.Fib379>() with provider { FibonacciJava.Fib379(instance(), instance()) }
    bind<FibonacciJava.Fib380>() with provider { FibonacciJava.Fib380(instance(), instance()) }
    bind<FibonacciJava.Fib381>() with provider { FibonacciJava.Fib381(instance(), instance()) }
    bind<FibonacciJava.Fib382>() with provider { FibonacciJava.Fib382(instance(), instance()) }
    bind<FibonacciJava.Fib383>() with provider { FibonacciJava.Fib383(instance(), instance()) }
    bind<FibonacciJava.Fib384>() with provider { FibonacciJava.Fib384(instance(), instance()) }
    bind<FibonacciJava.Fib385>() with provider { FibonacciJava.Fib385(instance(), instance()) }
    bind<FibonacciJava.Fib386>() with provider { FibonacciJava.Fib386(instance(), instance()) }
    bind<FibonacciJava.Fib387>() with provider { FibonacciJava.Fib387(instance(), instance()) }
    bind<FibonacciJava.Fib388>() with provider { FibonacciJava.Fib388(instance(), instance()) }
    bind<FibonacciJava.Fib389>() with provider { FibonacciJava.Fib389(instance(), instance()) }
    bind<FibonacciJava.Fib390>() with provider { FibonacciJava.Fib390(instance(), instance()) }
    bind<FibonacciJava.Fib391>() with provider { FibonacciJava.Fib391(instance(), instance()) }
    bind<FibonacciJava.Fib392>() with provider { FibonacciJava.Fib392(instance(), instance()) }
    bind<FibonacciJava.Fib393>() with provider { FibonacciJava.Fib393(instance(), instance()) }
    bind<FibonacciJava.Fib394>() with provider { FibonacciJava.Fib394(instance(), instance()) }
    bind<FibonacciJava.Fib395>() with provider { FibonacciJava.Fib395(instance(), instance()) }
    bind<FibonacciJava.Fib396>() with provider { FibonacciJava.Fib396(instance(), instance()) }
    bind<FibonacciJava.Fib397>() with provider { FibonacciJava.Fib397(instance(), instance()) }
    bind<FibonacciJava.Fib398>() with provider { FibonacciJava.Fib398(instance(), instance()) }
    bind<FibonacciJava.Fib399>() with provider { FibonacciJava.Fib399(instance(), instance()) }
    bind<FibonacciJava.Fib400>() with provider { FibonacciJava.Fib400(instance(), instance()) }
    bind<FibonacciJava.Fib401>() with provider { FibonacciJava.Fib401(instance(), instance()) }
    bind<FibonacciJava.Fib402>() with provider { FibonacciJava.Fib402(instance(), instance()) }
    bind<FibonacciJava.Fib403>() with provider { FibonacciJava.Fib403(instance(), instance()) }
    bind<FibonacciJava.Fib404>() with provider { FibonacciJava.Fib404(instance(), instance()) }
    bind<FibonacciJava.Fib405>() with provider { FibonacciJava.Fib405(instance(), instance()) }
    bind<FibonacciJava.Fib406>() with provider { FibonacciJava.Fib406(instance(), instance()) }
    bind<FibonacciJava.Fib407>() with provider { FibonacciJava.Fib407(instance(), instance()) }
    bind<FibonacciJava.Fib408>() with provider { FibonacciJava.Fib408(instance(), instance()) }
    bind<FibonacciJava.Fib409>() with provider { FibonacciJava.Fib409(instance(), instance()) }
    bind<FibonacciJava.Fib410>() with provider { FibonacciJava.Fib410(instance(), instance()) }
    bind<FibonacciJava.Fib411>() with provider { FibonacciJava.Fib411(instance(), instance()) }
    bind<FibonacciJava.Fib412>() with provider { FibonacciJava.Fib412(instance(), instance()) }
    bind<FibonacciJava.Fib413>() with provider { FibonacciJava.Fib413(instance(), instance()) }
    bind<FibonacciJava.Fib414>() with provider { FibonacciJava.Fib414(instance(), instance()) }
    bind<FibonacciJava.Fib415>() with provider { FibonacciJava.Fib415(instance(), instance()) }
    bind<FibonacciJava.Fib416>() with provider { FibonacciJava.Fib416(instance(), instance()) }
    bind<FibonacciJava.Fib417>() with provider { FibonacciJava.Fib417(instance(), instance()) }
    bind<FibonacciJava.Fib418>() with provider { FibonacciJava.Fib418(instance(), instance()) }
    bind<FibonacciJava.Fib419>() with provider { FibonacciJava.Fib419(instance(), instance()) }
    bind<FibonacciJava.Fib420>() with provider { FibonacciJava.Fib420(instance(), instance()) }
    bind<FibonacciJava.Fib421>() with provider { FibonacciJava.Fib421(instance(), instance()) }
    bind<FibonacciJava.Fib422>() with provider { FibonacciJava.Fib422(instance(), instance()) }
    bind<FibonacciJava.Fib423>() with provider { FibonacciJava.Fib423(instance(), instance()) }
    bind<FibonacciJava.Fib424>() with provider { FibonacciJava.Fib424(instance(), instance()) }
    bind<FibonacciJava.Fib425>() with provider { FibonacciJava.Fib425(instance(), instance()) }
    bind<FibonacciJava.Fib426>() with provider { FibonacciJava.Fib426(instance(), instance()) }
    bind<FibonacciJava.Fib427>() with provider { FibonacciJava.Fib427(instance(), instance()) }
    bind<FibonacciJava.Fib428>() with provider { FibonacciJava.Fib428(instance(), instance()) }
    bind<FibonacciJava.Fib429>() with provider { FibonacciJava.Fib429(instance(), instance()) }
    bind<FibonacciJava.Fib430>() with provider { FibonacciJava.Fib430(instance(), instance()) }
    bind<FibonacciJava.Fib431>() with provider { FibonacciJava.Fib431(instance(), instance()) }
    bind<FibonacciJava.Fib432>() with provider { FibonacciJava.Fib432(instance(), instance()) }
    bind<FibonacciJava.Fib433>() with provider { FibonacciJava.Fib433(instance(), instance()) }
    bind<FibonacciJava.Fib434>() with provider { FibonacciJava.Fib434(instance(), instance()) }
    bind<FibonacciJava.Fib435>() with provider { FibonacciJava.Fib435(instance(), instance()) }
    bind<FibonacciJava.Fib436>() with provider { FibonacciJava.Fib436(instance(), instance()) }
    bind<FibonacciJava.Fib437>() with provider { FibonacciJava.Fib437(instance(), instance()) }
    bind<FibonacciJava.Fib438>() with provider { FibonacciJava.Fib438(instance(), instance()) }
    bind<FibonacciJava.Fib439>() with provider { FibonacciJava.Fib439(instance(), instance()) }
    bind<FibonacciJava.Fib440>() with provider { FibonacciJava.Fib440(instance(), instance()) }
    bind<FibonacciJava.Fib441>() with provider { FibonacciJava.Fib441(instance(), instance()) }
    bind<FibonacciJava.Fib442>() with provider { FibonacciJava.Fib442(instance(), instance()) }
    bind<FibonacciJava.Fib443>() with provider { FibonacciJava.Fib443(instance(), instance()) }
    bind<FibonacciJava.Fib444>() with provider { FibonacciJava.Fib444(instance(), instance()) }
    bind<FibonacciJava.Fib445>() with provider { FibonacciJava.Fib445(instance(), instance()) }
    bind<FibonacciJava.Fib446>() with provider { FibonacciJava.Fib446(instance(), instance()) }
    bind<FibonacciJava.Fib447>() with provider { FibonacciJava.Fib447(instance(), instance()) }
    bind<FibonacciJava.Fib448>() with provider { FibonacciJava.Fib448(instance(), instance()) }
    bind<FibonacciJava.Fib449>() with provider { FibonacciJava.Fib449(instance(), instance()) }
    bind<FibonacciJava.Fib450>() with provider { FibonacciJava.Fib450(instance(), instance()) }
}
