package com.sloydev.dependencyinjectionperformance.kodein

import org.kodein.di.Kodein
import org.kodein.di.erased.bind
import org.kodein.di.erased.instance
import org.kodein.di.erased.provider
import com.sloydev.dependencyinjectionperformance.*

/**
 * Generated with https://gist.github.com/Sloy/12affca1e49ba052053ab4c8bfc5bcb4
 */
val kodeinKotlinModule = Kodein.Module("fib") {
    bind<Fib1>() with provider { Fib1() }
    bind<Fib2>() with provider { Fib2() }
    bind<Fib3>() with provider { Fib3(instance(), instance()) }
    bind<Fib4>() with provider { Fib4(instance(), instance()) }
    bind<Fib5>() with provider { Fib5(instance(), instance()) }
    bind<Fib6>() with provider { Fib6(instance(), instance()) }
    bind<Fib7>() with provider { Fib7(instance(), instance()) }
    bind<Fib8>() with provider { Fib8(instance(), instance()) }
    bind<Fib9>() with provider { Fib9(instance(), instance()) }
    bind<Fib10>() with provider { Fib10(instance(), instance()) }
    bind<Fib11>() with provider { Fib11(instance(), instance()) }
    bind<Fib12>() with provider { Fib12(instance(), instance()) }
    bind<Fib13>() with provider { Fib13(instance(), instance()) }
    bind<Fib14>() with provider { Fib14(instance(), instance()) }
    bind<Fib15>() with provider { Fib15(instance(), instance()) }
    bind<Fib16>() with provider { Fib16(instance(), instance()) }
    bind<Fib17>() with provider { Fib17(instance(), instance()) }
    bind<Fib18>() with provider { Fib18(instance(), instance()) }
    bind<Fib19>() with provider { Fib19(instance(), instance()) }
    bind<Fib20>() with provider { Fib20(instance(), instance()) }
    bind<Fib21>() with provider { Fib21(instance(), instance()) }
    bind<Fib22>() with provider { Fib22(instance(), instance()) }
    bind<Fib23>() with provider { Fib23(instance(), instance()) }
    bind<Fib24>() with provider { Fib24(instance(), instance()) }
    bind<Fib25>() with provider { Fib25(instance(), instance()) }
    bind<Fib26>() with provider { Fib26(instance(), instance()) }
    bind<Fib27>() with provider { Fib27(instance(), instance()) }
    bind<Fib28>() with provider { Fib28(instance(), instance()) }
    bind<Fib29>() with provider { Fib29(instance(), instance()) }
    bind<Fib30>() with provider { Fib30(instance(), instance()) }
    bind<Fib31>() with provider { Fib31(instance(), instance()) }
    bind<Fib32>() with provider { Fib32(instance(), instance()) }
    bind<Fib33>() with provider { Fib33(instance(), instance()) }
    bind<Fib34>() with provider { Fib34(instance(), instance()) }
    bind<Fib35>() with provider { Fib35(instance(), instance()) }
    bind<Fib36>() with provider { Fib36(instance(), instance()) }
    bind<Fib37>() with provider { Fib37(instance(), instance()) }
    bind<Fib38>() with provider { Fib38(instance(), instance()) }
    bind<Fib39>() with provider { Fib39(instance(), instance()) }
    bind<Fib40>() with provider { Fib40(instance(), instance()) }
    bind<Fib41>() with provider { Fib41(instance(), instance()) }
    bind<Fib42>() with provider { Fib42(instance(), instance()) }
    bind<Fib43>() with provider { Fib43(instance(), instance()) }
    bind<Fib44>() with provider { Fib44(instance(), instance()) }
    bind<Fib45>() with provider { Fib45(instance(), instance()) }
    bind<Fib46>() with provider { Fib46(instance(), instance()) }
    bind<Fib47>() with provider { Fib47(instance(), instance()) }
    bind<Fib48>() with provider { Fib48(instance(), instance()) }
    bind<Fib49>() with provider { Fib49(instance(), instance()) }
    bind<Fib50>() with provider { Fib50(instance(), instance()) }
    bind<Fib51>() with provider { Fib51(instance(), instance()) }
    bind<Fib52>() with provider { Fib52(instance(), instance()) }
    bind<Fib53>() with provider { Fib53(instance(), instance()) }
    bind<Fib54>() with provider { Fib54(instance(), instance()) }
    bind<Fib55>() with provider { Fib55(instance(), instance()) }
    bind<Fib56>() with provider { Fib56(instance(), instance()) }
    bind<Fib57>() with provider { Fib57(instance(), instance()) }
    bind<Fib58>() with provider { Fib58(instance(), instance()) }
    bind<Fib59>() with provider { Fib59(instance(), instance()) }
    bind<Fib60>() with provider { Fib60(instance(), instance()) }
    bind<Fib61>() with provider { Fib61(instance(), instance()) }
    bind<Fib62>() with provider { Fib62(instance(), instance()) }
    bind<Fib63>() with provider { Fib63(instance(), instance()) }
    bind<Fib64>() with provider { Fib64(instance(), instance()) }
    bind<Fib65>() with provider { Fib65(instance(), instance()) }
    bind<Fib66>() with provider { Fib66(instance(), instance()) }
    bind<Fib67>() with provider { Fib67(instance(), instance()) }
    bind<Fib68>() with provider { Fib68(instance(), instance()) }
    bind<Fib69>() with provider { Fib69(instance(), instance()) }
    bind<Fib70>() with provider { Fib70(instance(), instance()) }
    bind<Fib71>() with provider { Fib71(instance(), instance()) }
    bind<Fib72>() with provider { Fib72(instance(), instance()) }
    bind<Fib73>() with provider { Fib73(instance(), instance()) }
    bind<Fib74>() with provider { Fib74(instance(), instance()) }
    bind<Fib75>() with provider { Fib75(instance(), instance()) }
    bind<Fib76>() with provider { Fib76(instance(), instance()) }
    bind<Fib77>() with provider { Fib77(instance(), instance()) }
    bind<Fib78>() with provider { Fib78(instance(), instance()) }
    bind<Fib79>() with provider { Fib79(instance(), instance()) }
    bind<Fib80>() with provider { Fib80(instance(), instance()) }
    bind<Fib81>() with provider { Fib81(instance(), instance()) }
    bind<Fib82>() with provider { Fib82(instance(), instance()) }
    bind<Fib83>() with provider { Fib83(instance(), instance()) }
    bind<Fib84>() with provider { Fib84(instance(), instance()) }
    bind<Fib85>() with provider { Fib85(instance(), instance()) }
    bind<Fib86>() with provider { Fib86(instance(), instance()) }
    bind<Fib87>() with provider { Fib87(instance(), instance()) }
    bind<Fib88>() with provider { Fib88(instance(), instance()) }
    bind<Fib89>() with provider { Fib89(instance(), instance()) }
    bind<Fib90>() with provider { Fib90(instance(), instance()) }
    bind<Fib91>() with provider { Fib91(instance(), instance()) }
    bind<Fib92>() with provider { Fib92(instance(), instance()) }
    bind<Fib93>() with provider { Fib93(instance(), instance()) }
    bind<Fib94>() with provider { Fib94(instance(), instance()) }
    bind<Fib95>() with provider { Fib95(instance(), instance()) }
    bind<Fib96>() with provider { Fib96(instance(), instance()) }
    bind<Fib97>() with provider { Fib97(instance(), instance()) }
    bind<Fib98>() with provider { Fib98(instance(), instance()) }
    bind<Fib99>() with provider { Fib99(instance(), instance()) }
    bind<Fib100>() with provider { Fib100(instance(), instance()) }
    bind<Fib101>() with provider { Fib101(instance(), instance()) }
    bind<Fib102>() with provider { Fib102(instance(), instance()) }
    bind<Fib103>() with provider { Fib103(instance(), instance()) }
    bind<Fib104>() with provider { Fib104(instance(), instance()) }
    bind<Fib105>() with provider { Fib105(instance(), instance()) }
    bind<Fib106>() with provider { Fib106(instance(), instance()) }
    bind<Fib107>() with provider { Fib107(instance(), instance()) }
    bind<Fib108>() with provider { Fib108(instance(), instance()) }
    bind<Fib109>() with provider { Fib109(instance(), instance()) }
    bind<Fib110>() with provider { Fib110(instance(), instance()) }
    bind<Fib111>() with provider { Fib111(instance(), instance()) }
    bind<Fib112>() with provider { Fib112(instance(), instance()) }
    bind<Fib113>() with provider { Fib113(instance(), instance()) }
    bind<Fib114>() with provider { Fib114(instance(), instance()) }
    bind<Fib115>() with provider { Fib115(instance(), instance()) }
    bind<Fib116>() with provider { Fib116(instance(), instance()) }
    bind<Fib117>() with provider { Fib117(instance(), instance()) }
    bind<Fib118>() with provider { Fib118(instance(), instance()) }
    bind<Fib119>() with provider { Fib119(instance(), instance()) }
    bind<Fib120>() with provider { Fib120(instance(), instance()) }
    bind<Fib121>() with provider { Fib121(instance(), instance()) }
    bind<Fib122>() with provider { Fib122(instance(), instance()) }
    bind<Fib123>() with provider { Fib123(instance(), instance()) }
    bind<Fib124>() with provider { Fib124(instance(), instance()) }
    bind<Fib125>() with provider { Fib125(instance(), instance()) }
    bind<Fib126>() with provider { Fib126(instance(), instance()) }
    bind<Fib127>() with provider { Fib127(instance(), instance()) }
    bind<Fib128>() with provider { Fib128(instance(), instance()) }
    bind<Fib129>() with provider { Fib129(instance(), instance()) }
    bind<Fib130>() with provider { Fib130(instance(), instance()) }
    bind<Fib131>() with provider { Fib131(instance(), instance()) }
    bind<Fib132>() with provider { Fib132(instance(), instance()) }
    bind<Fib133>() with provider { Fib133(instance(), instance()) }
    bind<Fib134>() with provider { Fib134(instance(), instance()) }
    bind<Fib135>() with provider { Fib135(instance(), instance()) }
    bind<Fib136>() with provider { Fib136(instance(), instance()) }
    bind<Fib137>() with provider { Fib137(instance(), instance()) }
    bind<Fib138>() with provider { Fib138(instance(), instance()) }
    bind<Fib139>() with provider { Fib139(instance(), instance()) }
    bind<Fib140>() with provider { Fib140(instance(), instance()) }
    bind<Fib141>() with provider { Fib141(instance(), instance()) }
    bind<Fib142>() with provider { Fib142(instance(), instance()) }
    bind<Fib143>() with provider { Fib143(instance(), instance()) }
    bind<Fib144>() with provider { Fib144(instance(), instance()) }
    bind<Fib145>() with provider { Fib145(instance(), instance()) }
    bind<Fib146>() with provider { Fib146(instance(), instance()) }
    bind<Fib147>() with provider { Fib147(instance(), instance()) }
    bind<Fib148>() with provider { Fib148(instance(), instance()) }
    bind<Fib149>() with provider { Fib149(instance(), instance()) }
    bind<Fib150>() with provider { Fib150(instance(), instance()) }
    bind<Fib151>() with provider { Fib151(instance(), instance()) }
    bind<Fib152>() with provider { Fib152(instance(), instance()) }
    bind<Fib153>() with provider { Fib153(instance(), instance()) }
    bind<Fib154>() with provider { Fib154(instance(), instance()) }
    bind<Fib155>() with provider { Fib155(instance(), instance()) }
    bind<Fib156>() with provider { Fib156(instance(), instance()) }
    bind<Fib157>() with provider { Fib157(instance(), instance()) }
    bind<Fib158>() with provider { Fib158(instance(), instance()) }
    bind<Fib159>() with provider { Fib159(instance(), instance()) }
    bind<Fib160>() with provider { Fib160(instance(), instance()) }
    bind<Fib161>() with provider { Fib161(instance(), instance()) }
    bind<Fib162>() with provider { Fib162(instance(), instance()) }
    bind<Fib163>() with provider { Fib163(instance(), instance()) }
    bind<Fib164>() with provider { Fib164(instance(), instance()) }
    bind<Fib165>() with provider { Fib165(instance(), instance()) }
    bind<Fib166>() with provider { Fib166(instance(), instance()) }
    bind<Fib167>() with provider { Fib167(instance(), instance()) }
    bind<Fib168>() with provider { Fib168(instance(), instance()) }
    bind<Fib169>() with provider { Fib169(instance(), instance()) }
    bind<Fib170>() with provider { Fib170(instance(), instance()) }
    bind<Fib171>() with provider { Fib171(instance(), instance()) }
    bind<Fib172>() with provider { Fib172(instance(), instance()) }
    bind<Fib173>() with provider { Fib173(instance(), instance()) }
    bind<Fib174>() with provider { Fib174(instance(), instance()) }
    bind<Fib175>() with provider { Fib175(instance(), instance()) }
    bind<Fib176>() with provider { Fib176(instance(), instance()) }
    bind<Fib177>() with provider { Fib177(instance(), instance()) }
    bind<Fib178>() with provider { Fib178(instance(), instance()) }
    bind<Fib179>() with provider { Fib179(instance(), instance()) }
    bind<Fib180>() with provider { Fib180(instance(), instance()) }
    bind<Fib181>() with provider { Fib181(instance(), instance()) }
    bind<Fib182>() with provider { Fib182(instance(), instance()) }
    bind<Fib183>() with provider { Fib183(instance(), instance()) }
    bind<Fib184>() with provider { Fib184(instance(), instance()) }
    bind<Fib185>() with provider { Fib185(instance(), instance()) }
    bind<Fib186>() with provider { Fib186(instance(), instance()) }
    bind<Fib187>() with provider { Fib187(instance(), instance()) }
    bind<Fib188>() with provider { Fib188(instance(), instance()) }
    bind<Fib189>() with provider { Fib189(instance(), instance()) }
    bind<Fib190>() with provider { Fib190(instance(), instance()) }
    bind<Fib191>() with provider { Fib191(instance(), instance()) }
    bind<Fib192>() with provider { Fib192(instance(), instance()) }
    bind<Fib193>() with provider { Fib193(instance(), instance()) }
    bind<Fib194>() with provider { Fib194(instance(), instance()) }
    bind<Fib195>() with provider { Fib195(instance(), instance()) }
    bind<Fib196>() with provider { Fib196(instance(), instance()) }
    bind<Fib197>() with provider { Fib197(instance(), instance()) }
    bind<Fib198>() with provider { Fib198(instance(), instance()) }
    bind<Fib199>() with provider { Fib199(instance(), instance()) }
    bind<Fib200>() with provider { Fib200(instance(), instance()) }
    bind<Fib201>() with provider { Fib201(instance(), instance()) }
    bind<Fib202>() with provider { Fib202(instance(), instance()) }
    bind<Fib203>() with provider { Fib203(instance(), instance()) }
    bind<Fib204>() with provider { Fib204(instance(), instance()) }
    bind<Fib205>() with provider { Fib205(instance(), instance()) }
    bind<Fib206>() with provider { Fib206(instance(), instance()) }
    bind<Fib207>() with provider { Fib207(instance(), instance()) }
    bind<Fib208>() with provider { Fib208(instance(), instance()) }
    bind<Fib209>() with provider { Fib209(instance(), instance()) }
    bind<Fib210>() with provider { Fib210(instance(), instance()) }
    bind<Fib211>() with provider { Fib211(instance(), instance()) }
    bind<Fib212>() with provider { Fib212(instance(), instance()) }
    bind<Fib213>() with provider { Fib213(instance(), instance()) }
    bind<Fib214>() with provider { Fib214(instance(), instance()) }
    bind<Fib215>() with provider { Fib215(instance(), instance()) }
    bind<Fib216>() with provider { Fib216(instance(), instance()) }
    bind<Fib217>() with provider { Fib217(instance(), instance()) }
    bind<Fib218>() with provider { Fib218(instance(), instance()) }
    bind<Fib219>() with provider { Fib219(instance(), instance()) }
    bind<Fib220>() with provider { Fib220(instance(), instance()) }
    bind<Fib221>() with provider { Fib221(instance(), instance()) }
    bind<Fib222>() with provider { Fib222(instance(), instance()) }
    bind<Fib223>() with provider { Fib223(instance(), instance()) }
    bind<Fib224>() with provider { Fib224(instance(), instance()) }
    bind<Fib225>() with provider { Fib225(instance(), instance()) }
    bind<Fib226>() with provider { Fib226(instance(), instance()) }
    bind<Fib227>() with provider { Fib227(instance(), instance()) }
    bind<Fib228>() with provider { Fib228(instance(), instance()) }
    bind<Fib229>() with provider { Fib229(instance(), instance()) }
    bind<Fib230>() with provider { Fib230(instance(), instance()) }
    bind<Fib231>() with provider { Fib231(instance(), instance()) }
    bind<Fib232>() with provider { Fib232(instance(), instance()) }
    bind<Fib233>() with provider { Fib233(instance(), instance()) }
    bind<Fib234>() with provider { Fib234(instance(), instance()) }
    bind<Fib235>() with provider { Fib235(instance(), instance()) }
    bind<Fib236>() with provider { Fib236(instance(), instance()) }
    bind<Fib237>() with provider { Fib237(instance(), instance()) }
    bind<Fib238>() with provider { Fib238(instance(), instance()) }
    bind<Fib239>() with provider { Fib239(instance(), instance()) }
    bind<Fib240>() with provider { Fib240(instance(), instance()) }
    bind<Fib241>() with provider { Fib241(instance(), instance()) }
    bind<Fib242>() with provider { Fib242(instance(), instance()) }
    bind<Fib243>() with provider { Fib243(instance(), instance()) }
    bind<Fib244>() with provider { Fib244(instance(), instance()) }
    bind<Fib245>() with provider { Fib245(instance(), instance()) }
    bind<Fib246>() with provider { Fib246(instance(), instance()) }
    bind<Fib247>() with provider { Fib247(instance(), instance()) }
    bind<Fib248>() with provider { Fib248(instance(), instance()) }
    bind<Fib249>() with provider { Fib249(instance(), instance()) }
    bind<Fib250>() with provider { Fib250(instance(), instance()) }
    bind<Fib251>() with provider { Fib251(instance(), instance()) }
    bind<Fib252>() with provider { Fib252(instance(), instance()) }
    bind<Fib253>() with provider { Fib253(instance(), instance()) }
    bind<Fib254>() with provider { Fib254(instance(), instance()) }
    bind<Fib255>() with provider { Fib255(instance(), instance()) }
    bind<Fib256>() with provider { Fib256(instance(), instance()) }
    bind<Fib257>() with provider { Fib257(instance(), instance()) }
    bind<Fib258>() with provider { Fib258(instance(), instance()) }
    bind<Fib259>() with provider { Fib259(instance(), instance()) }
    bind<Fib260>() with provider { Fib260(instance(), instance()) }
    bind<Fib261>() with provider { Fib261(instance(), instance()) }
    bind<Fib262>() with provider { Fib262(instance(), instance()) }
    bind<Fib263>() with provider { Fib263(instance(), instance()) }
    bind<Fib264>() with provider { Fib264(instance(), instance()) }
    bind<Fib265>() with provider { Fib265(instance(), instance()) }
    bind<Fib266>() with provider { Fib266(instance(), instance()) }
    bind<Fib267>() with provider { Fib267(instance(), instance()) }
    bind<Fib268>() with provider { Fib268(instance(), instance()) }
    bind<Fib269>() with provider { Fib269(instance(), instance()) }
    bind<Fib270>() with provider { Fib270(instance(), instance()) }
    bind<Fib271>() with provider { Fib271(instance(), instance()) }
    bind<Fib272>() with provider { Fib272(instance(), instance()) }
    bind<Fib273>() with provider { Fib273(instance(), instance()) }
    bind<Fib274>() with provider { Fib274(instance(), instance()) }
    bind<Fib275>() with provider { Fib275(instance(), instance()) }
    bind<Fib276>() with provider { Fib276(instance(), instance()) }
    bind<Fib277>() with provider { Fib277(instance(), instance()) }
    bind<Fib278>() with provider { Fib278(instance(), instance()) }
    bind<Fib279>() with provider { Fib279(instance(), instance()) }
    bind<Fib280>() with provider { Fib280(instance(), instance()) }
    bind<Fib281>() with provider { Fib281(instance(), instance()) }
    bind<Fib282>() with provider { Fib282(instance(), instance()) }
    bind<Fib283>() with provider { Fib283(instance(), instance()) }
    bind<Fib284>() with provider { Fib284(instance(), instance()) }
    bind<Fib285>() with provider { Fib285(instance(), instance()) }
    bind<Fib286>() with provider { Fib286(instance(), instance()) }
    bind<Fib287>() with provider { Fib287(instance(), instance()) }
    bind<Fib288>() with provider { Fib288(instance(), instance()) }
    bind<Fib289>() with provider { Fib289(instance(), instance()) }
    bind<Fib290>() with provider { Fib290(instance(), instance()) }
    bind<Fib291>() with provider { Fib291(instance(), instance()) }
    bind<Fib292>() with provider { Fib292(instance(), instance()) }
    bind<Fib293>() with provider { Fib293(instance(), instance()) }
    bind<Fib294>() with provider { Fib294(instance(), instance()) }
    bind<Fib295>() with provider { Fib295(instance(), instance()) }
    bind<Fib296>() with provider { Fib296(instance(), instance()) }
    bind<Fib297>() with provider { Fib297(instance(), instance()) }
    bind<Fib298>() with provider { Fib298(instance(), instance()) }
    bind<Fib299>() with provider { Fib299(instance(), instance()) }
    bind<Fib300>() with provider { Fib300(instance(), instance()) }
    bind<Fib301>() with provider { Fib301(instance(), instance()) }
    bind<Fib302>() with provider { Fib302(instance(), instance()) }
    bind<Fib303>() with provider { Fib303(instance(), instance()) }
    bind<Fib304>() with provider { Fib304(instance(), instance()) }
    bind<Fib305>() with provider { Fib305(instance(), instance()) }
    bind<Fib306>() with provider { Fib306(instance(), instance()) }
    bind<Fib307>() with provider { Fib307(instance(), instance()) }
    bind<Fib308>() with provider { Fib308(instance(), instance()) }
    bind<Fib309>() with provider { Fib309(instance(), instance()) }
    bind<Fib310>() with provider { Fib310(instance(), instance()) }
    bind<Fib311>() with provider { Fib311(instance(), instance()) }
    bind<Fib312>() with provider { Fib312(instance(), instance()) }
    bind<Fib313>() with provider { Fib313(instance(), instance()) }
    bind<Fib314>() with provider { Fib314(instance(), instance()) }
    bind<Fib315>() with provider { Fib315(instance(), instance()) }
    bind<Fib316>() with provider { Fib316(instance(), instance()) }
    bind<Fib317>() with provider { Fib317(instance(), instance()) }
    bind<Fib318>() with provider { Fib318(instance(), instance()) }
    bind<Fib319>() with provider { Fib319(instance(), instance()) }
    bind<Fib320>() with provider { Fib320(instance(), instance()) }
    bind<Fib321>() with provider { Fib321(instance(), instance()) }
    bind<Fib322>() with provider { Fib322(instance(), instance()) }
    bind<Fib323>() with provider { Fib323(instance(), instance()) }
    bind<Fib324>() with provider { Fib324(instance(), instance()) }
    bind<Fib325>() with provider { Fib325(instance(), instance()) }
    bind<Fib326>() with provider { Fib326(instance(), instance()) }
    bind<Fib327>() with provider { Fib327(instance(), instance()) }
    bind<Fib328>() with provider { Fib328(instance(), instance()) }
    bind<Fib329>() with provider { Fib329(instance(), instance()) }
    bind<Fib330>() with provider { Fib330(instance(), instance()) }
    bind<Fib331>() with provider { Fib331(instance(), instance()) }
    bind<Fib332>() with provider { Fib332(instance(), instance()) }
    bind<Fib333>() with provider { Fib333(instance(), instance()) }
    bind<Fib334>() with provider { Fib334(instance(), instance()) }
    bind<Fib335>() with provider { Fib335(instance(), instance()) }
    bind<Fib336>() with provider { Fib336(instance(), instance()) }
    bind<Fib337>() with provider { Fib337(instance(), instance()) }
    bind<Fib338>() with provider { Fib338(instance(), instance()) }
    bind<Fib339>() with provider { Fib339(instance(), instance()) }
    bind<Fib340>() with provider { Fib340(instance(), instance()) }
    bind<Fib341>() with provider { Fib341(instance(), instance()) }
    bind<Fib342>() with provider { Fib342(instance(), instance()) }
    bind<Fib343>() with provider { Fib343(instance(), instance()) }
    bind<Fib344>() with provider { Fib344(instance(), instance()) }
    bind<Fib345>() with provider { Fib345(instance(), instance()) }
    bind<Fib346>() with provider { Fib346(instance(), instance()) }
    bind<Fib347>() with provider { Fib347(instance(), instance()) }
    bind<Fib348>() with provider { Fib348(instance(), instance()) }
    bind<Fib349>() with provider { Fib349(instance(), instance()) }
    bind<Fib350>() with provider { Fib350(instance(), instance()) }
    bind<Fib351>() with provider { Fib351(instance(), instance()) }
    bind<Fib352>() with provider { Fib352(instance(), instance()) }
    bind<Fib353>() with provider { Fib353(instance(), instance()) }
    bind<Fib354>() with provider { Fib354(instance(), instance()) }
    bind<Fib355>() with provider { Fib355(instance(), instance()) }
    bind<Fib356>() with provider { Fib356(instance(), instance()) }
    bind<Fib357>() with provider { Fib357(instance(), instance()) }
    bind<Fib358>() with provider { Fib358(instance(), instance()) }
    bind<Fib359>() with provider { Fib359(instance(), instance()) }
    bind<Fib360>() with provider { Fib360(instance(), instance()) }
    bind<Fib361>() with provider { Fib361(instance(), instance()) }
    bind<Fib362>() with provider { Fib362(instance(), instance()) }
    bind<Fib363>() with provider { Fib363(instance(), instance()) }
    bind<Fib364>() with provider { Fib364(instance(), instance()) }
    bind<Fib365>() with provider { Fib365(instance(), instance()) }
    bind<Fib366>() with provider { Fib366(instance(), instance()) }
    bind<Fib367>() with provider { Fib367(instance(), instance()) }
    bind<Fib368>() with provider { Fib368(instance(), instance()) }
    bind<Fib369>() with provider { Fib369(instance(), instance()) }
    bind<Fib370>() with provider { Fib370(instance(), instance()) }
    bind<Fib371>() with provider { Fib371(instance(), instance()) }
    bind<Fib372>() with provider { Fib372(instance(), instance()) }
    bind<Fib373>() with provider { Fib373(instance(), instance()) }
    bind<Fib374>() with provider { Fib374(instance(), instance()) }
    bind<Fib375>() with provider { Fib375(instance(), instance()) }
    bind<Fib376>() with provider { Fib376(instance(), instance()) }
    bind<Fib377>() with provider { Fib377(instance(), instance()) }
    bind<Fib378>() with provider { Fib378(instance(), instance()) }
    bind<Fib379>() with provider { Fib379(instance(), instance()) }
    bind<Fib380>() with provider { Fib380(instance(), instance()) }
    bind<Fib381>() with provider { Fib381(instance(), instance()) }
    bind<Fib382>() with provider { Fib382(instance(), instance()) }
    bind<Fib383>() with provider { Fib383(instance(), instance()) }
    bind<Fib384>() with provider { Fib384(instance(), instance()) }
    bind<Fib385>() with provider { Fib385(instance(), instance()) }
    bind<Fib386>() with provider { Fib386(instance(), instance()) }
    bind<Fib387>() with provider { Fib387(instance(), instance()) }
    bind<Fib388>() with provider { Fib388(instance(), instance()) }
    bind<Fib389>() with provider { Fib389(instance(), instance()) }
    bind<Fib390>() with provider { Fib390(instance(), instance()) }
    bind<Fib391>() with provider { Fib391(instance(), instance()) }
    bind<Fib392>() with provider { Fib392(instance(), instance()) }
    bind<Fib393>() with provider { Fib393(instance(), instance()) }
    bind<Fib394>() with provider { Fib394(instance(), instance()) }
    bind<Fib395>() with provider { Fib395(instance(), instance()) }
    bind<Fib396>() with provider { Fib396(instance(), instance()) }
    bind<Fib397>() with provider { Fib397(instance(), instance()) }
    bind<Fib398>() with provider { Fib398(instance(), instance()) }
    bind<Fib399>() with provider { Fib399(instance(), instance()) }
    bind<Fib400>() with provider { Fib400(instance(), instance()) }
    bind<Fib401>() with provider { Fib401(instance(), instance()) }
    bind<Fib402>() with provider { Fib402(instance(), instance()) }
    bind<Fib403>() with provider { Fib403(instance(), instance()) }
    bind<Fib404>() with provider { Fib404(instance(), instance()) }
    bind<Fib405>() with provider { Fib405(instance(), instance()) }
    bind<Fib406>() with provider { Fib406(instance(), instance()) }
    bind<Fib407>() with provider { Fib407(instance(), instance()) }
    bind<Fib408>() with provider { Fib408(instance(), instance()) }
    bind<Fib409>() with provider { Fib409(instance(), instance()) }
    bind<Fib410>() with provider { Fib410(instance(), instance()) }
    bind<Fib411>() with provider { Fib411(instance(), instance()) }
    bind<Fib412>() with provider { Fib412(instance(), instance()) }
    bind<Fib413>() with provider { Fib413(instance(), instance()) }
    bind<Fib414>() with provider { Fib414(instance(), instance()) }
    bind<Fib415>() with provider { Fib415(instance(), instance()) }
    bind<Fib416>() with provider { Fib416(instance(), instance()) }
    bind<Fib417>() with provider { Fib417(instance(), instance()) }
    bind<Fib418>() with provider { Fib418(instance(), instance()) }
    bind<Fib419>() with provider { Fib419(instance(), instance()) }
    bind<Fib420>() with provider { Fib420(instance(), instance()) }
    bind<Fib421>() with provider { Fib421(instance(), instance()) }
    bind<Fib422>() with provider { Fib422(instance(), instance()) }
    bind<Fib423>() with provider { Fib423(instance(), instance()) }
    bind<Fib424>() with provider { Fib424(instance(), instance()) }
    bind<Fib425>() with provider { Fib425(instance(), instance()) }
    bind<Fib426>() with provider { Fib426(instance(), instance()) }
    bind<Fib427>() with provider { Fib427(instance(), instance()) }
    bind<Fib428>() with provider { Fib428(instance(), instance()) }
    bind<Fib429>() with provider { Fib429(instance(), instance()) }
    bind<Fib430>() with provider { Fib430(instance(), instance()) }
    bind<Fib431>() with provider { Fib431(instance(), instance()) }
    bind<Fib432>() with provider { Fib432(instance(), instance()) }
    bind<Fib433>() with provider { Fib433(instance(), instance()) }
    bind<Fib434>() with provider { Fib434(instance(), instance()) }
    bind<Fib435>() with provider { Fib435(instance(), instance()) }
    bind<Fib436>() with provider { Fib436(instance(), instance()) }
    bind<Fib437>() with provider { Fib437(instance(), instance()) }
    bind<Fib438>() with provider { Fib438(instance(), instance()) }
    bind<Fib439>() with provider { Fib439(instance(), instance()) }
    bind<Fib440>() with provider { Fib440(instance(), instance()) }
    bind<Fib441>() with provider { Fib441(instance(), instance()) }
    bind<Fib442>() with provider { Fib442(instance(), instance()) }
    bind<Fib443>() with provider { Fib443(instance(), instance()) }
    bind<Fib444>() with provider { Fib444(instance(), instance()) }
    bind<Fib445>() with provider { Fib445(instance(), instance()) }
    bind<Fib446>() with provider { Fib446(instance(), instance()) }
    bind<Fib447>() with provider { Fib447(instance(), instance()) }
    bind<Fib448>() with provider { Fib448(instance(), instance()) }
    bind<Fib449>() with provider { Fib449(instance(), instance()) }
    bind<Fib450>() with provider { Fib450(instance(), instance()) }
}
